name: nuntium
description: A News Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  get: ^4.6.5
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  internet_connection_checker_plus: ^1.0.1
  firebase_core: ^2.14.0
  flutter_local_notifications: ^15.1.0+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  firebase_auth: ^4.6.3
  pinput: ^2.2.31
  cloud_firestore: ^4.8.2
  easy_localization: ^3.0.2
  webview_flutter: ^4.2.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  infinite_scroll_pagination: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  quickalert: ^1.0.1
  lottie: ^2.4.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/images/vectors/
    - assets/translation/



  fonts:
    - family: SP_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
